								--Quản lí thư viện - Thực tập nhóm

--QLTV_TTN
--nhân viên
--sinh viên 
--sách 
--mượn trả 
--vị trí
--phiếu mượn sách
--đăng nhập 
Create Database QLTV_TTN
go
use QLTV_TTN 
go

	Create table DANGNHAP
	(
	TaiKhoan NVARCHAR(30),
	MatKhau VARCHAR(30)
	)
go

	Create table NHANVIEN
	(
	MANV VARCHAR(8) PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH NVARCHAR(5) CHECK (GIOITINH IN (N'Nam',N'Nữ')),
	NGAYSINH DATE,
	DIENTHOAI VARCHAR(11)
	)
GO
	Create table SINHVIEN
	(
	MASV VARCHAR(8) PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH NVARCHAR(5) CHECK (GIOITINH IN (N'Nam',N'Nữ')),
	NGAYSINH DATE,
	DIENTHOAI VARCHAR(11),
	LOP NVARCHAR(50)
	)
go

	Create table SACH
	(
	MASACH VARCHAR(8) PRIMARY KEY NOT NULL,
	TENSACH NVARCHAR(50) NOT NULL,
	TACGIA NVARCHAR(50),
	THELOAI NVARCHAR(50),
	MAVT VARCHAR(8) REFERENCES VITRISACH(MAVT) ON DELETE CASCADE,
	NXB NVARCHAR(50),
	NAMXB DATE,
	SOLUONG INT
	)
go

	Create table VITRISACH
	(
	MAVT VARCHAR(8) PRIMARY KEY NOT NULL,
	VITRI NVARCHAR(50),
	TENKE NVARCHAR(50),

	)
go
	Create table MUONTRA
	(
	 PRIMARY KEY(MAPM,MASACH),
	 MAPM VARCHAR(8) REFERENCES PHIEUMUON(MAPM) ON DELETE CASCADE,
	 MASACH VARCHAR(8) REFERENCES SACH(MASACH) ON DELETE CASCADE,
	 NGAYMUON DATE,
	 NGAYTRA DATE,
	 TIENPHAT VARCHAR(8)
	)
GO
ALTER TABLE dbo.MUONTRA ADD MASV VARCHAR(8)
ALTER TABLE dbo.MUONTRA ALTER COLUMN TIENPHAT FLOAT 
	Create table PHIEUMUON
	(
	 MAPM VARCHAR(8) PRIMARY KEY NOT NULL,
	 MANV VARCHAR(8) REFERENCES NHANVIEN(MANV) ON DELETE CASCADE,
	 MASV VARCHAR(8) REFERENCES SINHVIEN(MASV) ON DELETE CASCADE,
	 NGAYMUON DATE,
	 MASACH VARCHAR(50),
	 TENSACH NVARCHAR(100)

	)
go
	--insert DANGNHAP
	INSERT dbo.DANGNHAP( TaiKhoan, MatKhau )
	VALUES  ( N'admin','123456'),
			( N'user1','123456')
GO

	--insert NHANVIEN
	INSERT INTO NHANVIEN VALUES ('NV01',N'Sơn Tùng','Nam','1995-2-2','0165315415');
	INSERT INTO NHANVIEN VALUES ('NV02',N'Bích Phương',N'Nữ','1992-11-22','0981413520');
	INSERT INTO NHANVIEN VALUES ('NV03',N'Đàm Vĩnh Hưng','Nam','5-2-1997','01234512852');
	INSERT INTO NHANVIEN VALUES ('NV04',N'Chi Pu','Nam','1-2-1995','0982014165');
	INSERT INTO NHANVIEN VALUES ('NV05',N'Noo Phước Thịnh','Nam','1-7-2000','0978500132');
go

	--Proc DANGNHAP
	CREATE PROC DangKy(@Taikhoan NVARCHAR(30),@Matkhau NVARCHAR(30))
	AS
	BEGIN
		INSERT dbo.DANGNHAP( TaiKhoan, MatKhau )
		VALUES  ( @Taikhoan, @Matkhau )
	END
GO

	CREATE PROC dbo.KiemTraDN(@Username VARCHAR(50),@Pass varchar(50)) AS 
	BEGIN
		SELECT * FROM dbo.DANGNHAP WHERE TaiKhoan = @Username AND MatKhau = @Pass
	END
GO
	--Proc NHANVIEN
	CREATE PROCEDURE ADD_NHANVIEN(@MANV VARCHAR(8),@HOTEN NVARCHAR(50),@GIOITINH NVARCHAR(5),@NGAYSINH DATE,@DIENTHOAI VARCHAR(11))
AS
BEGIN
		INSERT INTO NHANVIEN
		VALUES(@MANV,@HOTEN,@GIOITINH,@NGAYSINH,@DIENTHOAI)
END
GO
	--Sua
CREATE PROCEDURE ALTER_NHANVIEN(@MANV VARCHAR(8),@HOTEN NVARCHAR(50),@GIOITINH NVARCHAR(5),@NGAYSINH DATE,@DIENTHOAI VARCHAR(11))
AS
BEGIN
	UPDATE NHANVIEN
	SET HOTEN=@HOTEN,GIOITINH=@GIOITINH,NGAYSINH=@NGAYSINH,DIENTHOAI =@DIENTHOAI
	WHERE MANV=@MANV
			
END	
GO	
	--Xoa
CREATE PROCEDURE D_NHANVIEN(@MANV VARCHAR(8))
AS
BEGIN 
	DELETE FROM NHANVIEN
	WHERE MANV=@MANV
END		
GO
 

-----------------Sach
	--Them
CREATE PROCEDURE ThemSach(@MASACH VARCHAR(8),@TENSACH NVARCHAR(50),@TACGIA NVARCHAR(50),@THELOAI NVARCHAR(50),@MAVT VARCHAR(8),@NXB NVARCHAR(50),@NAMXB DATE,@SOLUONG INT)
AS
BEGIN
		INSERT INTO SACH
		VALUES(@MASACH,@TENSACH,@TACGIA,@THELOAI,@MAVT,@NXB,@NAMXB,@SOLUONG)
END
GO
	--Sua
CREATE PROCEDURE SuaSach(@MASACH VARCHAR(8),@TENSACH NVARCHAR(50),@TACGIA NVARCHAR(50),@THELOAI NVARCHAR(50),@MAVT VARCHAR(8),@NXB NVARCHAR(50),@NAMXB DATE,@SOLUONG INT)
AS
BEGIN
	UPDATE SACH
	SET MASACH=@MASACH,TENSACH=@TENSACH,TACGIA=@TACGIA,THELOAI=@THELOAI,MAVT=@MAVT,NXB=@NXB,NAMXB=@NAMXB,SOLUONG=@SOLUONG
	WHERE MASACH=@MASACH			
END	
GO	
	--Xoa
CREATE PROCEDURE XoaSach(@MASACH VARCHAR(8))
AS
BEGIN 
	DELETE FROM SACH
	WHERE MASACH=@MASACH
END		
GO


CREATE PROC MuonSach( @MAPM varchar(8), @MANV varchar(8), @MASV varchar(8), @NGAYMUON DATE,@MASACH varchar(10),@TENSACH NVARCHAR(50)) AS
BEGIN
	INSERT INTO dbo.PHIEUMUON 
	VALUES( @MAPM, @MANV, @MASV, @NGAYMUON,@MASACH,@TENSACH ) 
END

CREATE PROC TraSach( @MAPM varchar(8),@MASACH varchar(8), @NGAYMUON date, @NGAYTRA date,@TIENPHAT float,@MASV varchar(8))AS
BEGIN
	INSERT INTO dbo.MUONTRA ( MAPM ,MASACH , NGAYMUON , NGAYTRA ,TIENPHAT,MASV )
	VALUES  ( @MAPM ,@MASACH , @NGAYMUON , @NGAYTRA , @TIENPHAT, @MASV )
END

CREATE PROC XoaPM(@MAPM varchar(8))AS
BEGIN
DELETE dbo.PHIEUMUON WHERE MAPM = @MAPM
END


 INSERT dbo.SINHVIEN 
 VALUES  ( 'SV01' ,  N'Lê Hồng Phong' , N'Nam' , '1997/11/11' , '0123456789' ,N'KHMT 14-3' )
  INSERT dbo.SINHVIEN 
 VALUES  ( 'SV02' ,  N'Tạ Hải Đăng' , N'Nam' , '1996/11/12' , '022222222' ,N'KHMT 14-3' )
  INSERT dbo.SINHVIEN 
 VALUES  ( 'SV03' ,  N'Nguyễn Hương Giang' , N'Nữ' , '1995/9/3' , '0123456789' ,N'CNTT 14-2' )



 INSERT INTO dbo.VITRISACH
         ( MAVT, VITRI, TENKE )
 VALUES  ( 'VT03', N'03',N'A3'  )
  INSERT INTO dbo.VITRISACH
         ( MAVT, VITRI, TENKE )
 VALUES  ( 'VT04', N'04',N'A4'  )
  INSERT INTO dbo.VITRISACH
         ( MAVT, VITRI, TENKE )
 VALUES  ( 'VT05', N'05',N'A5'  )
  INSERT INTO dbo.VITRISACH
         ( MAVT, VITRI, TENKE )
 VALUES  ( 'VT06', N'06',N'A6'  )
  INSERT INTO dbo.VITRISACH
         ( MAVT, VITRI, TENKE )
 VALUES  ( 'VT07', N'07',N'A7'  )
  INSERT INTO dbo.VITRISACH
         ( MAVT, VITRI, TENKE )
 VALUES  ( 'VT08', N'08',N'A8'  )


 INSERT INTO dbo.SACH       
 VALUES  ( 'S02' ,N'Tây du ký' , N'Ngô Thừa Ân' , N'Du ký' , 'VT02' , N'Đại Lục' , '1968/02/03' , 10000  )
 INSERT INTO dbo.SACH       
 VALUES  ( 'S03' ,N'Chị Dậu' , N'Ngô Tất Tố' , N'Văn Học' , 'VT03' , N'Kim Dồng' , '1975/09/03' , 100  )
  INSERT INTO dbo.SACH       
 VALUES  ( 'S04' ,N'Lão Hạc' , N'Nam Cao' , N'Văn Học xưa' , 'VT04' , N'Giáo Dục' , '1954/06/03' , 100  )
  INSERT INTO dbo.SACH       
 VALUES  ( 'S05' ,N'Sóng' , N'Xuân Quỳnh' , N'Thơ' , 'VT05' , N'Giáo Dục' , '1997/07/11' , 100  )
  INSERT INTO dbo.SACH       
 VALUES  ( 'S06' ,N'Bánh Trôi Nước' , N'Bà Huyện Thanh Quan' , N'Trào Phúng' , 'VT07' , N'Giáo Dục' , '1950/02/03' , 100  )
  INSERT INTO dbo.SACH       
 VALUES  ( 'S07' ,N'Hoa Học Trò' , N'Nguyễn Kim Anh' , N'Báo chí' , 'VT02' , N'Thanh Niên' , '2015/02/03' , 10000  )
  
 