								--Quản lí thư viện - Thực tập nhóm

--QLTV_TTN
--nhân viên
--sinh viên 
--sách 
--mượn trả 
--vị trí
--phiếu mượn sách
--đăng nhập 
Create Database QLTV_TTN
go
use QLTV_TTN
go

	Create table DANGNHAP
	(
	TaiKhoan NVARCHAR(30),
	MatKhau VARCHAR(30)
	)
go
	Create table NHANVIEN
	(
	MANV VARCHAR(8) PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH NVARCHAR(5) CHECK (GIOITINH IN (N'Nam',N'Nữ')),
	NGAYSINH DATE,
	DIENTHOAI VARCHAR(8)
	)
GO
	Create table SINHVIEN
	(
	MASV VARCHAR(8) PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH NVARCHAR(5) CHECK (GIOITINH IN (N'Nam',N'Nữ')),
	NGAYSINH DATE,
	DIENTHOAI VARCHAR(8),
	LOP NVARCHAR(50)
	)
go

	Create table SACH
	(
	MASACH VARCHAR(8) PRIMARY KEY NOT NULL,
	TENSACH NVARCHAR(50) NOT NULL,
	TACGIA NVARCHAR(50),
	THELOAI NVARCHAR(50),
	MAVT VARCHAR(8) REFERENCES VITRISACH(MAVT) ON DELETE CASCADE,
	NXB NVARCHAR(50),
	NAMXB DATE,
	SOLUONG INT
	)
go

	Create table VITRISACH
	(
	MAVT VARCHAR(8) PRIMARY KEY NOT NULL,
	VITRI NVARCHAR(50),
	TENKE NVARCHAR(50),

	)
go
	Create table MUONTRA
	(
	 PRIMARY KEY(MAPM,MASACH),
	 MAPM VARCHAR(8) REFERENCES PHIEUMUON(MAPM) ON DELETE CASCADE,
	 MASACH VARCHAR(8) REFERENCES SACH(MASACH) ON DELETE CASCADE,
	 NGAYMUON DATE,
	 NGAYTRA DATE,
	 TIENPHAT VARCHAR(8)
	)
go
	Create table PHIEUMUON
	(
	 MAPM VARCHAR(8) PRIMARY KEY NOT NULL,
	 MANV VARCHAR(8) REFERENCES NHANVIEN(MANV) ON DELETE CASCADE,
	 MASV VARCHAR(8) REFERENCES SINHVIEN(MASV) ON DELETE CASCADE,
	 NGAYMUON DATE
	)
go

	--insert DANGNHAP
	INSERT dbo.DANGNHAP( TaiKhoan, MatKhau )
	VALUES  ( N'admin','123456'),
			( N'user1','123456')
GO
	--Proc DANGNHAP
	CREATE PROC DangKy(@Taikhoan NVARCHAR(30),@Matkhau NVARCHAR(30))
	AS
	BEGIN
		INSERT dbo.DANGNHAP( TaiKhoan, MatKhau )
		VALUES  ( @Taikhoan, @Matkhau )
	END
GO

	CREATE PROC dbo.KiemTraDN(@Username VARCHAR(50),@Pass varchar(50)) AS 
	BEGIN
		SELECT * FROM dbo.DANGNHAP WHERE TaiKhoan = @Username AND MatKhau = @Pass
	END
GO